### ISSUE TITLE
Handling unconfirmed user login.

### ISSUE THREAD

**Issue by franckstifler** [dashbitco/mix_phx_gen_auth_demo#3]
Hi, currently using this library for auth in an app. I have some questions regarding login for unconfirmed users (users with confirmed_at nil).
It's mentioned in the controller **auth_user** that the function *require_authenticated_user* is a good place to handle unconfirmed users. Citing the generated docs: "If you want to enforce the user e-mail is confirmed before they use the application at all, here would be a good place"
Looking at the pipelines, the unconfirmed user will be authenticated, and assigned into the **assigns** map, before reaching **require_authenticated_user**, just maybe to be then logout again (which I supposed is a way to enforce the user does not use the app)
So my questions are:
- Am I missing the use case of the **require_authenticated_user** in the case of unconfirmed users?
- Should a non-authorized user go through the pipelines (login, assigning sessions...) before being logged out? What could be the way to handle this otherwise?
- And in case we're login out the user, what is an appropriate way to provide feedback to the user for him to verify his account? Since we're clearing the session in logout.
Thanks for the amazing library.

**Comment by josevalim** [comment]
Hi @franckstifler ! Please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you.

But note you don’t have to logout the user if they are unconfirmed. Just keep redirecting them to the home page or the settings page until they confirm. Thank you!
